version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.6

workflows:
  build-and-publish:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          requires: [orb-tools/lint]
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          requires: [orb-tools/pack]
          context: orb-publish
          orb-ref: pennlabs/django@${CIRCLE_TAG}
          attach-workspace: true
          checkout: false
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
